/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUserRouteImport } from './routes/api/user'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiCronRouteImport } from './routes/api/cron'
import { Route as ApiContestsRouteImport } from './routes/api/contests'
import { Route as ApiUserPreferencesRouteImport } from './routes/api/user/preferences'
import { Route as ApiCalendarSyncRouteImport } from './routes/api/calendar/sync'
import { Route as ApiAuthSignoutRouteImport } from './routes/api/auth/signout'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthSigninGoogleRouteImport } from './routes/api/auth/signin/google'
import { Route as ApiAuthConnectCalendarRouteImport } from './routes/api/auth/connect/calendar'
import { Route as ApiAuthCallbackGoogleRouteImport } from './routes/api/auth/callback/google'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserRoute = ApiUserRouteImport.update({
  id: '/api/user',
  path: '/api/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/api/cron',
  path: '/api/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContestsRoute = ApiContestsRouteImport.update({
  id: '/api/contests',
  path: '/api/contests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserPreferencesRoute = ApiUserPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => ApiUserRoute,
} as any)
const ApiCalendarSyncRoute = ApiCalendarSyncRouteImport.update({
  id: '/api/calendar/sync',
  path: '/api/calendar/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignoutRoute = ApiAuthSignoutRouteImport.update({
  id: '/api/auth/signout',
  path: '/api/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSigninGoogleRoute = ApiAuthSigninGoogleRouteImport.update({
  id: '/api/auth/signin/google',
  path: '/api/auth/signin/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthConnectCalendarRoute = ApiAuthConnectCalendarRouteImport.update({
  id: '/api/auth/connect/calendar',
  path: '/api/auth/connect/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackGoogleRoute = ApiAuthCallbackGoogleRouteImport.update({
  id: '/api/auth/callback/google',
  path: '/api/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/contests': typeof ApiContestsRoute
  '/api/cron': typeof ApiCronRoute
  '/api/health': typeof ApiHealthRoute
  '/api/user': typeof ApiUserRouteWithChildren
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/calendar/sync': typeof ApiCalendarSyncRoute
  '/api/user/preferences': typeof ApiUserPreferencesRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/auth/connect/calendar': typeof ApiAuthConnectCalendarRoute
  '/api/auth/signin/google': typeof ApiAuthSigninGoogleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/contests': typeof ApiContestsRoute
  '/api/cron': typeof ApiCronRoute
  '/api/health': typeof ApiHealthRoute
  '/api/user': typeof ApiUserRouteWithChildren
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/calendar/sync': typeof ApiCalendarSyncRoute
  '/api/user/preferences': typeof ApiUserPreferencesRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/auth/connect/calendar': typeof ApiAuthConnectCalendarRoute
  '/api/auth/signin/google': typeof ApiAuthSigninGoogleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/contests': typeof ApiContestsRoute
  '/api/cron': typeof ApiCronRoute
  '/api/health': typeof ApiHealthRoute
  '/api/user': typeof ApiUserRouteWithChildren
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/calendar/sync': typeof ApiCalendarSyncRoute
  '/api/user/preferences': typeof ApiUserPreferencesRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/auth/connect/calendar': typeof ApiAuthConnectCalendarRoute
  '/api/auth/signin/google': typeof ApiAuthSigninGoogleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/terms'
    | '/api/contests'
    | '/api/cron'
    | '/api/health'
    | '/api/user'
    | '/api/auth/session'
    | '/api/auth/signout'
    | '/api/calendar/sync'
    | '/api/user/preferences'
    | '/api/auth/callback/google'
    | '/api/auth/connect/calendar'
    | '/api/auth/signin/google'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/terms'
    | '/api/contests'
    | '/api/cron'
    | '/api/health'
    | '/api/user'
    | '/api/auth/session'
    | '/api/auth/signout'
    | '/api/calendar/sync'
    | '/api/user/preferences'
    | '/api/auth/callback/google'
    | '/api/auth/connect/calendar'
    | '/api/auth/signin/google'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/terms'
    | '/api/contests'
    | '/api/cron'
    | '/api/health'
    | '/api/user'
    | '/api/auth/session'
    | '/api/auth/signout'
    | '/api/calendar/sync'
    | '/api/user/preferences'
    | '/api/auth/callback/google'
    | '/api/auth/connect/calendar'
    | '/api/auth/signin/google'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiContestsRoute: typeof ApiContestsRoute
  ApiCronRoute: typeof ApiCronRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiUserRoute: typeof ApiUserRouteWithChildren
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthSignoutRoute: typeof ApiAuthSignoutRoute
  ApiCalendarSyncRoute: typeof ApiCalendarSyncRoute
  ApiAuthCallbackGoogleRoute: typeof ApiAuthCallbackGoogleRoute
  ApiAuthConnectCalendarRoute: typeof ApiAuthConnectCalendarRoute
  ApiAuthSigninGoogleRoute: typeof ApiAuthSigninGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user': {
      id: '/api/user'
      path: '/api/user'
      fullPath: '/api/user'
      preLoaderRoute: typeof ApiUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron': {
      id: '/api/cron'
      path: '/api/cron'
      fullPath: '/api/cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contests': {
      id: '/api/contests'
      path: '/api/contests'
      fullPath: '/api/contests'
      preLoaderRoute: typeof ApiContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/preferences': {
      id: '/api/user/preferences'
      path: '/preferences'
      fullPath: '/api/user/preferences'
      preLoaderRoute: typeof ApiUserPreferencesRouteImport
      parentRoute: typeof ApiUserRoute
    }
    '/api/calendar/sync': {
      id: '/api/calendar/sync'
      path: '/api/calendar/sync'
      fullPath: '/api/calendar/sync'
      preLoaderRoute: typeof ApiCalendarSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signout': {
      id: '/api/auth/signout'
      path: '/api/auth/signout'
      fullPath: '/api/auth/signout'
      preLoaderRoute: typeof ApiAuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signin/google': {
      id: '/api/auth/signin/google'
      path: '/api/auth/signin/google'
      fullPath: '/api/auth/signin/google'
      preLoaderRoute: typeof ApiAuthSigninGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/connect/calendar': {
      id: '/api/auth/connect/calendar'
      path: '/api/auth/connect/calendar'
      fullPath: '/api/auth/connect/calendar'
      preLoaderRoute: typeof ApiAuthConnectCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/google': {
      id: '/api/auth/callback/google'
      path: '/api/auth/callback/google'
      fullPath: '/api/auth/callback/google'
      preLoaderRoute: typeof ApiAuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiUserRouteChildren {
  ApiUserPreferencesRoute: typeof ApiUserPreferencesRoute
}

const ApiUserRouteChildren: ApiUserRouteChildren = {
  ApiUserPreferencesRoute: ApiUserPreferencesRoute,
}

const ApiUserRouteWithChildren =
  ApiUserRoute._addFileChildren(ApiUserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiContestsRoute: ApiContestsRoute,
  ApiCronRoute: ApiCronRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiUserRoute: ApiUserRouteWithChildren,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthSignoutRoute: ApiAuthSignoutRoute,
  ApiCalendarSyncRoute: ApiCalendarSyncRoute,
  ApiAuthCallbackGoogleRoute: ApiAuthCallbackGoogleRoute,
  ApiAuthConnectCalendarRoute: ApiAuthConnectCalendarRoute,
  ApiAuthSigninGoogleRoute: ApiAuthSigninGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
